### ISSUE TITLE
Camera functionality enhancements

### ISSUE THREAD

**Issue by guardianblue** [spice2x/spice2x.github.io#201]
Some ideas to follow up on TDJ camera fix.

- [x] Ability to choose camera (in case of multiple) / resolution / encoding / frame rate in game or in spicecfg #204 
- [x] Set CameraControl parameters such as focus and exposure  #204
- [x] Hardware accelerated decoding #206
- [ ] MJPG Support
- [ ] Set VideoProc parameters (white balance / saturation / gain etc.)
- [ ] Show camera content in toggle-able overlays
- [ ] Allow using Spout2 instead of actual camera
- [x] Allow different rendering mode (stretch / letterbox etc.) #212
- [x] Allow pre-render operations (flip / rotate) #221
- [ ] Reactivate camera if it is stuck

**Comment by guardianblue** [comment]
Should be doable, since the camera texture is already on a D3D9 Surface 

It's more like a UX design decision to allow how much flexibility. Might as well just allow user to use Spout2 as input (like in the original cam hook) instead of directly reading the camera, though a separate flag, if sophisticated usage is needed. Like having your favourite vtuber to cheer for you at the usual camera spot.

**Comment by guardianblue** [comment]
Thanks for the catch!
I am wrapping up my code to allow preserving camera properties over an overlay, will try to integrate ratio/offset setting as well

**Comment by guardianblue** [comment]
be mindful though, while the camera test shows a 4:3 window, the game expects a 1280 * 720 texture. I have tried 4:3 modes on my camera (Logitech stream cam) and the results aren't good.

i will add a patch to allow stretch/ letterboxing after your new release

**Comment by llm96** [comment]
Minor issue: latest version crashes if your privacy settings disallow access to cameras. Works as expected when enabled.

![1uRWrFREDE](https://github.com/user-attachments/assets/e42ebc9c-be85-42a1-a4f8-db62cdf1dce4)

```
[2024/08/07 12:43:57] I:iidx::tdjcam: MFEnumDeviceSources returned 1 device(s)
[2024/08/07 12:43:57] M:iidx::tdjcam: Created DeviceManager for DXVA
[2024/08/07 12:43:57] I:iidx::tdjcam: [top] Creating camera
[2024/08/07 12:43:57] M:iidx::tdjcam: [top] Symlink: \\?\usb#vid_046d&pid_085c&mi_00#7&2e13f802&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
[2024/08/07 12:43:57] W:iidx::tdjcam: [top] Failed to create camera: -2147024891
[2024/08/07 12:43:57] I:iidx::tdjcam: [top] Release camera
[2024/08/07 12:43:57] W:signal: exception raised: EXCEPTION_ACCESS_VIOLATION
[2024/08/07 12:43:57] I:signal: printing callstack
[2024/08/07 13:33:10] I:stackwalker: 00000000005E085E (spice64): (unknown): (unknown)
[2024/08/07 12:43:58] F:signal: end
[2024/08/07 12:43:58] F:spice: encountered a fatal error, you can close the window or press ctrl + c
```

**Comment by guardianblue** [comment]
> Minor issue: latest version crashes if your privacy settings disallow access to cameras. Works as expected when enabled.
> 
> ![1uRWrFREDE](https://private-user-images.githubusercontent.com/484335/355818219-e42ebc9c-be85-42a1-a4f8-db62cdf1dce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDEyMTYsIm5iZiI6MTcyMzA0MDkxNiwicGF0aCI6Ii80ODQzMzUvMzU1ODE4MjE5LWU0MmViYzljLWJlODUtNDJhMS1hNGY4LWRiNjJjZGYxZGNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxNDI4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGY1ZjUwYzBkYTBmZGJjN2M0ZTg4NDFmOTcwMDFlYTA3MzY5MTJmOGYzODIzOTkyZDFhOWE4ODA0NjU1NDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wg7IJALC2VUwkonRv2ZCK57TKvZLPidixUj6rNQqGOg)
> 
> ```
> [2024/08/07 12:43:57] I:iidx::tdjcam: MFEnumDeviceSources returned 1 device(s)
> [2024/08/07 12:43:57] M:iidx::tdjcam: Created DeviceManager for DXVA
> [2024/08/07 12:43:57] I:iidx::tdjcam: [top] Creating camera
> [2024/08/07 12:43:57] M:iidx::tdjcam: [top] Symlink: \\?\usb#vid_046d&pid_085c&mi_00#7&2e13f802&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
> [2024/08/07 12:43:57] W:iidx::tdjcam: [top] Failed to create camera: -2147024891
> [2024/08/07 12:43:57] I:iidx::tdjcam: [top] Release camera
> [2024/08/07 12:43:57] W:signal: exception raised: EXCEPTION_ACCESS_VIOLATION
> [2024/08/07 12:43:57] I:signal: printing callstack
> [2024/08/07 13:33:10] I:stackwalker: 00000000005E085E (spice64): (unknown): (unknown)
> [2024/08/07 12:43:58] F:signal: end
> [2024/08/07 12:43:58] F:spice: encountered a fatal error, you can close the window or press ctrl + c
> ```

Thanks for the findings, will fix soon

**Comment by guardianblue** [comment]
#214 should fix the crash when camera is denied by privacy settings
